const $=s=>document.querySelector(s);let rows=[],out=[],official=0;
function csvLine(s){let a=[],c='',q=false;for(let i=0;i<s.length;i++){let x=s[i];if(x=='"')q=!q;else if(x==','&&!q){a.push(c);c=''}else c+=x}a.push(c);return a}
function parseCSV(t){let l=t.replace(/\r/g,'').split('\n').filter(Boolean),h=csvLine(l[0]).map(x=>x.trim().toLowerCase());let names={date:['date','日期'],code:['code','代號','證券代號'],name:['name','名稱','證券名稱'],open:['open','開盤','開盤價'],high:['high','最高','最高價'],low:['low','最低','最低價'],close:['close','收盤','收盤價'],volume:['volume','成交量','成交股數']},ix={};for(let k in names)ix[k]=h.findIndex(x=>names[k].includes(x));return l.slice(1).map(x=>{let p=csvLine(x),n=v=>Number(String(v||'').replace(/,/g,''));return{date:p[ix.date],code:String(p[ix.code]||''),name:p[ix.name]||'',open:n(p[ix.open]),high:n(p[ix.high]),low:n(p[ix.low]),close:n(p[ix.close]),volume:n(p[ix.volume])}}).filter(x=>x.date&&x.code&&isFinite(x.close))}
function monthly(rs){let g={};rs.forEach(r=>{let d=new Date(r.date.replace(/\//g,'-'));if(isNaN(d))return;let k=r.code+'|'+d.getFullYear()+'-'+(d.getMonth()+1);(g[k]??=[]).push({...r,d})});let s={};Object.values(g).forEach(a=>{a.sort((x,y)=>x.d-y.d);let f=a[0],z=a.at(-1),x={code:f.code,name:f.name,date:z.d,open:f.open||f.close,high:Math.max(...a.map(v=>v.high||v.close)),low:Math.min(...a.map(v=>v.low||v.close)),close:z.close,volume:a.reduce((q,v)=>q+(v.volume||0),0)};(s[x.code]??=[]).push(x)});Object.values(s).forEach(a=>a.sort((x,y)=>x.date-y.date));return s}
const sma=(a,n,i)=>i<n-1?NaN:a.slice(i-n+1,i+1).reduce((x,y)=>x+y,0)/n;
function ema(a,n){let k=2/(n+1),p=a[0];return a.map((v,i)=>p=i?v*k+p*(1-k):v)}
function rsi(a,n=14){let o=Array(a.length).fill(NaN),g=0,l=0;for(let i=1;i<a.length;i++){let c=a[i]-a[i-1];if(i<=n){g+=Math.max(c,0);l+=Math.max(-c,0)}if(i==n){g/=n;l/=n;o[i]=l?100-100/(1+g/l):100}else if(i>n){g=(g*(n-1)+Math.max(c,0))/n;l=(l*(n-1)+Math.max(-c,0))/n;o[i]=l?100-100/(1+g/l):100}}return o}
function kd(a,n=9){let K=Array(a.length).fill(NaN),D=Array(a.length).fill(NaN),k=50,d=50;for(let i=n-1;i<a.length;i++){let w=a.slice(i-n+1,i+1),h=Math.max(...w.map(x=>x.high)),l=Math.min(...w.map(x=>x.low)),r=h==l?50:(a[i].close-l)/(h-l)*100;k=(2*k+r)/3;d=(2*d+k)/3;K[i]=k;D[i]=d}return{K,D}}
function calc(a){if(a.length<24)return null;let c=a.map(x=>x.close),v=a.map(x=>x.volume),i=a.length-1,p=i-1,R=rsi(c),S=kd(a),e12=ema(c,12),e26=ema(c,26),dif=c.map((_,j)=>e12[j]-e26[j]),sig=ema(dif,9),hist=dif.map((x,j)=>(x-sig[j])*2),ma5=sma(c,5,i),ma10=sma(c,10,i),ma20=sma(c,20,i),vr=v[i]/sma(v,6,i),rise=(c[i]/c[i-6]-1)*100,kcross=S.K[i]>S.D[i]&&S.K[p]<=S.D[p];let score=0;if(kcross)score+=15;if(kcross&&S.D[i]<=35)score+=10;if(R[i]>R[p])score+=8;if(R[i]>=45)score+=7;if(hist[i]>0)score+=12;else if(hist[i]>hist[p])score+=8;if(dif[i]>sig[i])score+=8;if(c[i]>ma5)score+=8;if(c[i]>ma10)score+=6;if(c[i]>ma20)score+=6;if(vr>=1.05)score+=10;if(rise<=80)score+=10;score=Math.min(100,Math.round(score));let state=score>=80?'強勢候選':score>=65?'轉強觀察':'初步成形',entry=rise>80?'漲幅偏大，等回測 5 月線':kcross&&hist[i]>0?'突破本月高點且量能不縮，分批進場':'等回測 5 月線量縮止跌';return{code:a[i].code,name:a[i].name,close:c[i],K:S.K[i],D:S.D[i],R:R[i],hist:hist[i],score,state,entry,rise}}
function scan(){let m=monthly(rows),min=+$ ('#minScore').value,kmax=+$ ('#kdMax').value,rmin=+$ ('#rsiMin').value,rmax=+$ ('#riseMax').value;out=Object.values(m).map(calc).filter(Boolean).filter(x=>x.score>=min&&x.D<=kmax&&x.R>=rmin&&x.rise<=rmax).sort((a,b)=>b.score-a.score);render(Object.keys(m).length)}
function render(stocks){let q=$('#search').value.trim();let a=out.filter(x=>!q||x.code.includes(q)||x.name.includes(q));$('#count').textContent=a.length;$('#rows').textContent=rows.length;$('#stocks').textContent=stocks??new Set(rows.map(x=>x.code)).size;$('#high').textContent=out.filter(x=>x.score>=80).length;$('#official').textContent=official;$('#body').innerHTML=a.map(x=>`<tr><td><b>${x.name}</b><br>${x.code}</td><td class="score">${x.score}</td><td>${x.close.toFixed(2)}</td><td class="${x.K>x.D?'good':''}">${x.K.toFixed(1)}/${x.D.toFixed(1)}</td><td>${x.R.toFixed(1)}</td><td class="${x.hist>=0?'good':'warn'}">${x.hist.toFixed(2)}</td><td>${x.state}</td><td>${x.entry}</td></tr>`).join('');$('#empty').style.display=a.length?'none':'block'}
async function sync(){try{let r=await fetch('/api/twse/daily'),d=await r.json();if(!r.ok)throw Error(d.error||'同步失敗');official=d.length;let map=new Map(rows.map(x=>[x.code+'|'+x.date,x]));d.forEach(x=>map.set(x.code+'|'+x.date,x));rows=[...map.values()];render();alert(`已同步 ${d.length} 檔上市個股當日行情`)}catch(e){alert(e.message)}}
function demo(){rows=[];let defs=[['1303','南亞',30],['2330','台積電',500],['2308','台達電',250],['3711','日月光投控',90],['2002','中鋼',22],['1101','台泥',28],['2303','聯電',40],['2884','玉山金',24],['2454','聯發科',600]];defs.forEach((d,z)=>{let p=d[2];for(let m=0;m<54;m++){let dt=new Date(2022,m,15);p*=1.005+(m>35?.012:0)+(Math.sin((m+z)*.4)*.01);let c=p*(.97+Math.random()*.06);rows.push({date:dt.toISOString().slice(0,10),code:d[0],name:d[1],open:p,high:Math.max(p,c)*1.04,low:Math.min(p,c)*.96,close:c,volume:5e6+Math.random()*2e7});p=c}});scan()}
$('#file').onchange=async e=>{rows=parseCSV(await e.target.files[0].text());scan()};$('#sync').onclick=sync;$('#demo').onclick=demo;$('#scan').onclick=scan;$('#search').oninput=()=>render();fetch('/api/health').then(r=>r.json()).then(()=>{$('#health').textContent='雲端正常';$('#health').className='good'}).catch(()=>$('#health').textContent='連線異常');demo();