const $=s=>document.querySelector(s);let rows=[],allStocks=[],out=[],official=0,mode='bottom';let watch=new Set(JSON.parse(localStorage.getItem('tw-watch-v5')||'[]'));
function csvLine(s){let a=[],c='',q=false;for(let i=0;i<s.length;i++){let x=s[i];if(x=='"')q=!q;else if(x==','&&!q){a.push(c);c=''}else c+=x}a.push(c);return a}
function parseCSV(t){let l=t.replace(/\r/g,'').split('\n').filter(Boolean),h=csvLine(l[0]).map(x=>x.trim().toLowerCase());let names={date:['date','日期'],code:['code','代號','證券代號'],name:['name','名稱','證券名稱'],open:['open','開盤','開盤價'],high:['high','最高','最高價'],low:['low','最低','最低價'],close:['close','收盤','收盤價'],volume:['volume','成交量','成交股數']},ix={};for(let k in names)ix[k]=h.findIndex(x=>names[k].includes(x));return l.slice(1).map(x=>{let p=csvLine(x),n=v=>Number(String(v||'').replace(/,/g,''));return{date:p[ix.date],code:String(p[ix.code]||'').trim(),name:(p[ix.name]||'').trim(),open:n(p[ix.open]),high:n(p[ix.high]),low:n(p[ix.low]),close:n(p[ix.close]),volume:n(p[ix.volume])}}).filter(x=>x.date&&x.code&&isFinite(x.close))}
function monthly(rs){let g={};rs.forEach(r=>{let d=new Date(r.date.replace(/\//g,'-'));if(isNaN(d))return;let k=r.code+'|'+d.getFullYear()+'-'+(d.getMonth()+1);(g[k]??=[]).push({...r,d})});let s={};Object.values(g).forEach(a=>{a.sort((x,y)=>x.d-y.d);let f=a[0],z=a.at(-1),x={code:f.code,name:f.name,date:z.d,open:f.open||f.close,high:Math.max(...a.map(v=>v.high||v.close)),low:Math.min(...a.map(v=>v.low||v.close)),close:z.close,volume:a.reduce((q,v)=>q+(v.volume||0),0)};(s[x.code]??=[]).push(x)});Object.values(s).forEach(a=>a.sort((x,y)=>x.date-y.date));return s}
const sma=(a,n,i)=>i<n-1?NaN:a.slice(i-n+1,i+1).reduce((x,y)=>x+y,0)/n;
function ema(a,n){let k=2/(n+1),p=a[0];return a.map((v,i)=>p=i?v*k+p*(1-k):v)}
function rsi(a,n=14){let o=Array(a.length).fill(NaN),g=0,l=0;for(let i=1;i<a.length;i++){let c=a[i]-a[i-1];if(i<=n){g+=Math.max(c,0);l+=Math.max(-c,0)}if(i==n){g/=n;l/=n;o[i]=l?100-100/(1+g/l):100}else if(i>n){g=(g*(n-1)+Math.max(c,0))/n;l=(l*(n-1)+Math.max(-c,0))/n;o[i]=l?100-100/(1+g/l):100}}return o}
function kd(a,n=9){let K=Array(a.length).fill(NaN),D=Array(a.length).fill(NaN),k=50,d=50;for(let i=n-1;i<a.length;i++){let w=a.slice(i-n+1,i+1),h=Math.max(...w.map(x=>x.high)),l=Math.min(...w.map(x=>x.low)),r=h==l?50:(a[i].close-l)/(h-l)*100;k=(2*k+r)/3;d=(2*d+k)/3;K[i]=k;D[i]=d}return{K,D}}
function calc(a){if(a.length<24)return null;let c=a.map(x=>x.close),v=a.map(x=>x.volume),i=a.length-1,p=i-1,R=rsi(c),S=kd(a),e12=ema(c,12),e26=ema(c,26),dif=c.map((_,j)=>e12[j]-e26[j]),sig=ema(dif,9),hist=dif.map((x,j)=>(x-sig[j])*2),ma5=sma(c,5,i),ma10=sma(c,10,i),ma20=sma(c,20,i),vr=v[i]/sma(v,6,i),rise=(c[i]/c[i-6]-1)*100,kcross=S.K[i]>S.D[i]&&S.K[p]<=S.D[p],maDist=(c[i]/ma5-1)*100;let score=0;if(kcross)score+=15;if(kcross&&S.D[i]<=35)score+=10;if(R[i]>R[p])score+=8;if(R[i]>=45)score+=7;if(hist[i]>0)score+=12;else if(hist[i]>hist[p])score+=8;if(dif[i]>sig[i])score+=8;if(c[i]>ma5)score+=8;if(c[i]>ma10)score+=6;if(c[i]>ma20)score+=6;if(vr>=1.05)score+=10;if(rise<=80)score+=10;score=Math.min(100,Math.round(score));let state=score>=80?'強勢候選':score>=65?'轉強觀察':'初步成形',entry=rise>80?'漲幅偏大，等回測 5 月線':kcross&&hist[i]>0?'突破本月高點且量能不縮，可分批':'等回測 5 月線量縮止跌';return{code:a[i].code,name:a[i].name||a[i].code,close:c[i],K:S.K[i],D:S.D[i],R:R[i],hist:hist[i],score,state,entry,rise,vr,ma5,ma10,ma20,maDist,kcross,macdUp:hist[i]>hist[p],above20:c[i]>ma20}}
function scan(){let m=monthly(rows);allStocks=Object.values(m).map(calc).filter(Boolean);let min=+$('#minScore').value,kmax=+$('#kdMax').value,rmin=+$('#rsiMin').value,rmax=+$('#riseMax').value,vmin=+$('#volMin').value;out=allStocks.filter(x=>{let base=x.score>=min&&x.R>=rmin&&x.rise<=rmax&&x.vr>=vmin;if(mode==='bottom')return base&&x.D<=kmax&&x.kcross;if(mode==='breakout')return base&&x.above20&&x.vr>=1.05;if(mode==='pullback')return base&&Math.abs(x.maDist)<=8;return base}).sort((a,b)=>b.score-a.score);render()}
function render(){let q=$('#search').value.trim(),limit=+$('#limit').value;let a=out.filter(x=>!q||x.code.includes(q)||x.name.includes(q)).slice(0,limit);$('#count').textContent=a.length;$('#rows').textContent=rows.length;$('#stocks').textContent=allStocks.length;$('#high').textContent=allStocks.filter(x=>x.score>=80).length;$('#watchCount').textContent=watch.size;$('#body').innerHTML=a.map(x=>`<tr><td><button class="star ${watch.has(x.code)?'on':''}" onclick="toggleWatch('${x.code}')">★</button></td><td><div class="stock" onclick="openDetail('${x.code}')">${x.name}<small>${x.code}</small></div></td><td class="score">${x.score}</td><td>${x.close.toFixed(2)}</td><td class="${x.K>x.D?'good':''}">${x.K.toFixed(1)}/${x.D.toFixed(1)}</td><td>${x.R.toFixed(1)}</td><td class="${x.hist>=0?'good':'warn'}">${x.hist.toFixed(2)}</td><td>${x.vr.toFixed(2)}</td><td>${x.state}</td><td>${x.entry}</td></tr>`).join('');$('#empty').style.display=a.length?'none':'block';renderWatch()}
window.toggleWatch=code=>{watch.has(code)?watch.delete(code):watch.add(code);localStorage.setItem('tw-watch-v5',JSON.stringify([...watch]));render()}
function renderWatch(){let a=allStocks.filter(x=>watch.has(x.code));$('#watchCards').innerHTML=a.length?a.map(x=>`<article class="watch-card"><h3>${x.name} ${x.code} <span class="score">${x.score}</span></h3><p>${x.state}｜收盤 ${x.close.toFixed(2)}｜KD ${x.K.toFixed(1)}/${x.D.toFixed(1)}</p><p>${x.entry}</p><button class="secondary" onclick="openDetail('${x.code}')">查看細節</button></article>`).join(''):'<p id="empty">尚未加入自選股</p>'}
window.openDetail=code=>{let x=allStocks.find(v=>v.code===code);if(!x)return;$('#detail').innerHTML=`<small>STOCK DETAIL</small><h2>${x.name} ${x.code}</h2><div class="metric-grid"><div class="metric">評分<b>${x.score}</b></div><div class="metric">收盤<b>${x.close.toFixed(2)}</b></div><div class="metric">KD<b>${x.K.toFixed(1)}/${x.D.toFixed(1)}</b></div><div class="metric">RSI<b>${x.R.toFixed(1)}</b></div><div class="metric">MACD<b>${x.hist.toFixed(2)}</b></div><div class="metric">量比<b>${x.vr.toFixed(2)}</b></div></div><h3>進場規劃</h3><p>${x.entry}</p><div class="note">建議採 30%／30%／40% 分批，停損以結構低點或前月低點為準。</div>`;$('#detailDialog').showModal()}
function similarity(a,b){let parts=[1-Math.min(Math.abs(a.K-b.K)/100,1),1-Math.min(Math.abs(a.D-b.D)/100,1),1-Math.min(Math.abs(a.R-b.R)/100,1),1-Math.min(Math.abs(a.hist-b.hist)/(Math.abs(a.hist)+Math.abs(b.hist)+1),1),1-Math.min(Math.abs(a.vr-b.vr)/3,1),1-Math.min(Math.abs(a.maDist-b.maDist)/40,1),1-Math.min(Math.abs(a.rise-b.rise)/150,1)];return Math.round(parts.reduce((s,x)=>s+x,0)/parts.length*100)}
function runSimilar(){let code=$('#similarCode').value.trim(),ref=allStocks.find(x=>x.code===code);if(!ref){alert('找不到參考股票，請先載入足夠歷史資料');return}let a=allStocks.filter(x=>x.code!==code).map(x=>({...x,sim:similarity(ref,x)})).sort((x,y)=>y.sim-x.sim).slice(0,20);$('#similarTitle').textContent=`參考：${ref.name} ${ref.code}`;$('#similarBody').innerHTML=a.map((x,i)=>`<tr><td>${i+1}</td><td><b>${x.name}</b><br>${x.code}</td><td class="similarity">${x.sim}%</td><td>${x.score}</td><td>${x.K.toFixed(1)}/${x.D.toFixed(1)}</td><td>${x.R.toFixed(1)}</td><td>${x.hist.toFixed(2)}</td><td>${x.vr.toFixed(2)}</td><td>${x.sim>=90?'高度相似':x.sim>=80?'相似型態':'部分相似'}</td></tr>`).join('');$('#similarEmpty').style.display=a.length?'none':'block'}
function exportCSV(){let h=['code','name','score','close','K','D','RSI','MACD','volume_ratio','state','entry'],data=[h,...out.map(x=>[x.code,x.name,x.score,x.close,x.K,x.D,x.R,x.hist,x.vr,x.state,x.entry])],csv=data.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='V5選股結果.csv';a.click()}
async function sync(){try{let r=await fetch('/api/twse/daily'),d=await r.json();if(!r.ok)throw Error(d.error||'同步失敗');official=d.length;let map=new Map(rows.map(x=>[x.code+'|'+x.date,x]));d.forEach(x=>map.set(x.code+'|'+x.date,x));rows=[...map.values()];scan();alert(`已同步 ${d.length} 檔上市個股當日行情`)}catch(e){alert(e.message)}}
function demo(){rows=[];let defs=[['1303','南亞',30],['2330','台積電',500],['2308','台達電',250],['3711','日月光投控',90],['2002','中鋼',22],['1101','台泥',28],['2303','聯電',40],['2884','玉山金',24],['2454','聯發科',600],['1301','台塑',40],['2327','國巨',300],['2382','廣達',110]];defs.forEach((d,z)=>{let p=d[2];for(let m=0;m<54;m++){let dt=new Date(2022,m,15);p*=1.005+(m>35?.010+(z%3)*.002:0)+(Math.sin((m+z)*.4)*.012);let c=p*(.97+Math.random()*.06);rows.push({date:dt.toISOString().slice(0,10),code:d[0],name:d[1],open:p,high:Math.max(p,c)*1.04,low:Math.min(p,c)*.96,close:c,volume:5e6+Math.random()*2e7});p=c}});scan()}
$('#file').onchange=async e=>{rows=parseCSV(await e.target.files[0].text());scan()};$('#sync').onclick=sync;$('#demo').onclick=demo;$('#scan').onclick=scan;$('#export').onclick=exportCSV;$('#search').oninput=render;$('#limit').onchange=render;$('#runSimilar').onclick=runSimilar;$('#closeDialog').onclick=()=>$('#detailDialog').close();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active')});document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;scan()});fetch('/api/health').then(r=>r.json()).then(()=>{$('#health').textContent='雲端正常';$('#health').classList.add('good')}).catch(()=>$('#health').textContent='連線異常');demo();